Add CVE-2024-6386
Ostorlab/agent_asteroid pull request #102
Opened 2024-08-28 15:28 UTC by nmasdoufi-ol

2024-08-28 16:46 UTC, 3asm requested changes

2024-08-28 16:46 UTC, 3asm commented on agent/exploits/cve_2024_6386.py
> +VULNERABLE_VERSIONS_REGEX = r"(?m)^Stable tag:\s+(0|[1-3](?:\.\d+){0,2}|4(?:\.(?:[0-5](?:\.\d+)?|6(?:\.(?:[0-9]|1[0-2]))?)?)?)$"
Oh my god. This is unreadable and should be burnt with fire :fire: .

Split each version with a separate regex :fire_extinguisher: , prioritize readability over writing smart regexp please.

2024-08-29 07:45 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6386.py
> +VULNERABLE_VERSIONS_REGEX = r"(?m)^Stable tag:\s+(0|[1-3](?:\.\d+){0,2}|4(?:\.(?:[0-5](?:\.\d+)?|6(?:\.(?:[0-9]|1[0-2]))?)?)?)$"
Done.

2024-08-29 10:11 UTC, 3asm approved these changes

2024-08-29 10:11 UTC, merged