Add CVE-2024-40711
Ostorlab/agent_asteroid pull request #111
Opened 2024-09-12 12:25 UTC by nmasdoufi-ol

2024-09-12 14:37 UTC, ErebusZ approved these changes

2024-09-12 15:14 UTC, 3asm requested changes

2024-09-12 15:14 UTC, 3asm commented on agent/exploits/cve_2024_40711.py
> +                self.check_request.headers.update(req.headers)
I don't get this code? Why are we copying the headers from the request?

2024-09-12 17:23 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_40711.py
> +                self.check_request.headers.update(req.headers)
What I had to add is the `X-Api-Version` header because that's the one that's supposed to be sent to check the `serverInfo` endpoint. these two lines should be removed.

2024-09-13 03:36 UTC, 3asm approved these changes

2024-09-13 03:36 UTC, merged