Add CVE-2023-25280
Ostorlab/agent_asteroid pull request #119
Opened 2024-10-01 12:33 UTC by nmasdoufi-ol

###Summary

This PR introduces an exploit for CVE-2023-25280, a command injection vulnerability in the D-Link DIR820LA1 router firmware version FW105B03. This vulnerability allows attackers to execute arbitrary commands with elevated privileges. The exploit is based on an in-depth analysis of the vulnerability, as no live targets were found for testing.

### Changes

- Implemented DLinkDIR820LA1CommandInjectionExploit class in agent/exploits/dlink_dir820la1_command_injection.py
- Added unit tests in tests/exploits/test_dlink_dir820la1_command_injection.py

### Implementation Details

The exploit script performs the following actions:

- Identifies D-Link DIR820LA1 instances by checking for a specific support link in the HTML.
- Scans the target by sending a POST request to /ping.ccp with a crafted payload designed to trigger the command injection vulnerability.
- Checks the response to determine if the target is vulnerable by looking for the presence of a specific keyword in the response body.

### Testing

The unit tests cover the following scenarios:

- Detecting a vulnerable D-Link DIR820LA1 instance
- Correctly identifying a non-vulnerable (safe) D-Link DIR820LA1 instance
- Handling request exceptions gracefully
- Rejecting targets that are not D-Link DIR820LA1 devices

As there were no live targets available for testing, the exploit was validated solely by the actual [analysis](https://github.com/migraine-sudo/D_Link_Vuln/tree/main/cmd%20Inject%20in%20pingV4Msg) that was made on this CVE:

2024-10-01 13:11 UTC, ybadaoui-ostorlab reviewed
please, can you test it on a target and share a screenshot in the description?

2024-10-01 13:13 UTC, PiranhaSa commented on agent/exploits/cve_2023_25280.py
> +        if "vulnerable" in resp.text:
instead of vulnerable can't we echo something more complicated like concatenate it with something random , so we are sure there is no FP .

2024-10-01 13:18 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2023_25280.py
> +        if "vulnerable" in resp.text:
+1

2024-10-01 13:45 UTC, nmasdoufi-ol commented on agent/exploits/cve_2023_25280.py
> +        if "vulnerable" in resp.text:
vulnerable seems fine. We are echoing it in a router's page.

2024-10-01 13:45 UTC, nmasdoufi-ol commented
> Please, can you test it on a target and share a screenshot in the description?

Read Description.

2024-10-02 09:09 UTC, elyousfi5 commented on agent/exploits/cve_2023_25280.py
> +            return []
```suggestion
        return []
```

2024-10-02 09:33 UTC, 3asm requested changes

2024-10-02 09:33 UTC, 3asm commented on agent/exploits/cve_2023_25280.py
> +        payload = {"ccp_act": "pingV4Msg", "ping_addr": "%0aecho vulnerable%0a"}
This approach is very false positive. Having something like echo 123*456*789 and then checking for the 44253432 is safer.

2024-10-02 10:41 UTC, nmasdoufi-ol commented on agent/exploits/cve_2023_25280.py
> +        payload = {"ccp_act": "pingV4Msg", "ping_addr": "%0aecho vulnerable%0a"}
Noted and fixed.

2024-10-02 13:23 UTC, 3asm approved these changes

2024-10-02 13:23 UTC, merged