Add detection for CVE-2024-9487
Ostorlab/agent_asteroid pull request #123
Opened 2024-10-15 13:02 UTC by ybadaoui-ostorlab

Adding a version based detection for CVE-2024-9487

2024-10-15 13:17 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_9487.py
> +DEFAULT_TIMEOUT = 90
use `datetime.timedelta(seconds=90)`

2024-10-15 15:17 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
Since your regex captures only a single group (`(\d+\.\d+\.\d+)`), you don’t need the tuple handling logic.

2024-10-15 15:19 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_9487.py
> +        if (matched := self.version_pattern.findall(resp.text)) is not None:
Since `findall()` returns a list, matched will never be `None`. Instead, you should check if it contains any elements.

2024-10-15 15:21 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_9487.py
> +                if version.parse(extracted_version) < version.parse("3.15"):
GitHub Enterprise Server versions before `3.15` are vulnerable, but your check focuses only on versions below `3.10`. This might miss other vulnerable versions, like `3.10.0` to `3.11.6`.

2024-10-15 15:53 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +                if version.parse(extracted_version) < version.parse("3.15"):
No this is not the case, if it's between 3.15 and 3.10 i do check if it's before the fix versions

2024-10-15 16:42 UTC, 3asm requested changes

2024-10-15 16:42 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +DEFAULT_TIMEOUT = 90
+1

2024-10-15 16:42 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +                if version.parse(extracted_version) < version.parse("3.15"):
Use const for the 3.15.

2024-10-15 16:42 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +                    if version.parse(extracted_version) < version.parse("3.10"):
This code is confusing, there is a map with fixed, then there is this. I don't get it.

2024-10-16 13:45 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
no it for when there is more than one version that match that regex

2024-10-16 14:44 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +                    if version.parse(extracted_version) < version.parse("3.10"):
the vulnerable versions are all lower than 3.15 and on those vulnerable versions the versions mentioned on FIXED_VERSIONS did release a fix in there minor version from 3.11 to 3.14.

2024-10-16 16:09 UTC, mohsinenar requested changes

2024-10-16 16:09 UTC, mohsinenar commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
How is that possible?? you only have one capturing group in your regext!

2024-10-16 16:09 UTC, mohsinenar commented on agent/exploits/cve_2024_9487.py
> +                        vulnerabilities.append(vulnerability)
You are reporting multiple vulnurabilities, for multiple versions that are found in a single target!
This is not right, you should have only one version and one vulnerability.

2024-10-16 16:27 UTC, 3asm requested changes

2024-10-16 16:27 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +MAX_NONFIXED_VERSION = "3.10"
Why not use a list of ranges of vulnerable versions.

[None, 3.10], [3.11, 3.11.6], ...

2024-10-16 16:27 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
The code is not readable this way I suggest using range for this.

2024-10-17 10:52 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
you are right, i was doing it just because findall return a list but on this case it will never match more than one, thanks!

2024-10-17 14:28 UTC, elyousfi5 commented on agent/exploits/cve_2024_9487.py
> +            if self.is_vulnerable(extracted_version):
```suggestion
            if self.is_vulnerable(extracted_version) is True:
```

2024-10-17 14:29 UTC, elyousfi5 requested changes

2024-10-17 14:29 UTC, elyousfi5 commented on agent/exploits/cve_2024_9487.py
> +    def is_vulnerable(self, extracted_version: str) -> bool:
this method can be private and it should be outside the class

2024-10-17 16:00 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +    def is_vulnerable(self, extracted_version: str) -> bool:
why it should be outside the class?

2024-10-17 16:05 UTC, mohsinenar requested changes

2024-10-17 16:05 UTC, mohsinenar commented on agent/exploits/cve_2024_9487.py
> +from packaging import version
Why not semver??

2024-10-17 16:47 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +from packaging import version
what do you mean?

2024-10-17 19:49 UTC, 3asm approved these changes

2024-10-17 19:49 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +from packaging import version
semver refers to a package that handles semantic versions. The version you are using are semantic version. Mouhcine comment is valid.

2024-10-17 19:49 UTC, 3asm commented on agent/exploits/cve_2024_9487.py
> +    def is_vulnerable(self, extracted_version: str) -> bool:
+1

2024-10-18 08:49 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +MAX_NONFIXED_VERSION = "3.10"
fixed please check again

2024-10-18 08:49 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9487.py
> +                if isinstance(extracted_version, tuple):
updated!

2024-10-18 09:08 UTC, 3asm approved these changes

2024-10-18 09:08 UTC, merged