Add version based detection for CVE-2024-9164
Ostorlab/agent_asteroid pull request #125
Opened 2024-10-21 10:17 UTC by ybadaoui-ostorlab

This PR adds detection logic for **CVE-2024-9164**, which affects GitLab EE versions allowing pipelines to run on arbitrary branches.

The detection works by:

1. Sending a GET request to the target’s `/users/sign_in page`.
2. Matching the response body against two sets of version hashes:
   - **Vulnerable versions**: We are certain these hashes correspond to vulnerable versions, and they are reported as critical.
   -  **Potentially vulnerable versions**: These hashes may correspond to either vulnerable or non-vulnerable versions, so they are flagged as potentially vulnerable.

2024-10-21 10:30 UTC, 3asm requested changes

2024-10-21 10:30 UTC, 3asm commented on agent/exploits/cve_2024_9164.py
> +                return vulnerabilities
Split the check, and report one as high and the other as potential. The way the code is written is not readable.

2024-10-21 10:37 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9164.py
> +                return vulnerabilities
If i split the checks i will repeat the same piece of code, and the vulnerability is critical not high please check this https://about.gitlab.com/releases/2024/10/09/patch-release-gitlab-17-4-2-released/#run-pipelines-on-arbitrary-branches

2024-10-21 12:30 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_9164.py
> +        for version_hash in all_hashes:
How about a for loop for `POTENTIALLY_VULN_VERSIONS_HASHES` and another one for `VULN_VERSIONS_HASHES` instead of one for `all_hashes`, this way you can report the critical ones and potential ones separately.

2024-10-21 13:18 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9164.py
> +        for version_hash in all_hashes:
i don't want to repeat the same piece of code twice so i did check inside that loop if the matched pattern is inside which list and i set the risk rating based on that

2024-10-22 04:04 UTC, 3asm requested changes

2024-10-22 04:04 UTC, 3asm commented on agent/exploits/cve_2024_9164.py
> +                return vulnerabilities
If code will be repeated, then wrap it in a method and call it.

2024-10-22 08:37 UTC, deadly-panda commented on agent/exploits/cve_2024_9164.py
> +        for version_hash in all_hashes:
agree with @nmasdoufi-ol .. cleaner ..

2024-10-22 09:58 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9164.py
> +        for version_hash in all_hashes:
fixed! thanks!

2024-10-22 09:58 UTC, ybadaoui-ostorlab commented on agent/exploits/cve_2024_9164.py
> +                return vulnerabilities
updated!

2024-10-22 10:51 UTC, 3asm approved these changes

2024-10-22 10:51 UTC, merged