Add detection for CVE-2024-8956 and CVE-2024-8957
Ostorlab/agent_asteroid pull request #131
Opened 2024-11-05 13:00 UTC by nmasdoufi-ol

## Agent Asteroid Implementation for CVE-2024-8956 and CVE-2024-8957

### Summary

This pull request introduces detection and exploitation support for two critical vulnerabilities in the ValueHD PTZ Camera firmware below version 6.3.40:

- **CVE-2024-8956**: Authentication Bypass
- **CVE-2024-8957**: Command Injection via NTP server configuration

Both vulnerabilities are cataloged as **CRITICAL** due to their potential impact on device security.

### Changes

1. **Detection Mechanisms**:
    - **Authentication Bypass**: Detects bypass vulnerability by checking for vulnerable firmware versions on the `/cgi-bin/param.cgi?get_device_conf` endpoint.
    - **Command Injection**: Attempts to execute a command by injecting code into the NTP configuration on the `/cgi-bin/param.cgi?post_network_other_conf` endpoint.
	- **Accept Pattern**: Matches against `versioninfo="SOC v\d+\.\d+\.\d+` to confirm firmware version compatibility.
	- **Version Validation**: Checks if the firmware version is below `6.3.40`, marking it as vulnerable if true.

2. **Metadata Adjustments**:
    - Added `reference` field to support both `str` and `list[str]` types for better handling of multiple CVE references.

3. **Enhancements in `webexploit.py`**:
    - Improved `_create_vulnerability()` method to support multiple references.
    - Added detailed NVD links for each CVE reference, enabling quick access to official CVE details.

![image](https://github.com/user-attachments/assets/eecc8436-48d6-46e3-a5e8-8351e25ccc83)

2024-11-05 13:05 UTC, PiranhaSa commented on agent/exploits/webexploit.py
>              },
You need to make sure it's a list not string

2024-11-05 13:13 UTC, nmasdoufi-ol commented on agent/exploits/webexploit.py
>              },
Good catch.

2024-11-05 13:23 UTC, ybadaoui-ostorlab commented on agent/exploits/webexploit.py
>              },
+1

2024-11-05 14:18 UTC, elyousfi5 commented on agent/exploits/vhd_ptz_exploit.py
> +            if resp.status_code == 200 and "Success" in resp.text:
check on .lower()
```suggestion
            if resp.status_code == 200 and "Success" in resp.text:
```

2024-11-05 14:24 UTC, nmasdoufi-ol commented on agent/exploits/vhd_ptz_exploit.py
> +            if resp.status_code == 200 and "Success" in resp.text:
No the response is like this: `{"Response":{"Result":"Success"}}`

2024-11-05 16:16 UTC, 3asm requested changes

2024-11-05 16:16 UTC, 3asm commented on agent/definitions.py
> +    reference: str | list[str]
Sorry but this is not clean, we simply need to switch to references of list[str] only and changes all the other code.

2024-11-05 17:48 UTC, ohachimOs commented on agent/exploits/vhd_ptz_exploit.py
> +            if resp.status_code == 200 and "Success" in resp.text:
Const

2024-11-07 07:46 UTC, nmasdoufi-ol commented on agent/exploits/vhd_ptz_exploit.py
> +            if resp.status_code == 200 and "Success" in resp.text:
understood

2024-11-07 07:52 UTC, closed without merging