Adding CVE-2024_42509
Ostorlab/agent_asteroid pull request #135
Opened 2024-11-13 14:24 UTC by PiranhaSa

Vulnerability Summary: This PR implements an exploit check for CVE-2024-42509, an unauthenticated command injection vulnerability in HPE Aruba Networking Access Points. The vulnerability allows remote code execution due to a command injection flaw in the underlying CLI service. Specifically, the vulnerability is triggered by sending specially crafted packets to UDP port 8211, used by Aruba's Access Point management protocol (PAPI). However, due to the lack of a publicly available  (PoC) for the exploit, direct testing on UDP port 8211 is not feasible in this implementation.

Approach: To determine if a target device is running a vulnerable version of ArubaOS (AOS), we leveraged the SNMP (Simple Network Management Protocol) service. SNMP provides a reliable way to retrieve the AOS version by querying the system description, which can be accessed via the standard sysDescr OID. This OID reveals details about the device's OS, including the version of ArubaOS running on the access point.

Rationale: By querying SNMP to determine the AOS version, we can indirectly assess whether the device is susceptible to CVE-2024-42509. Once we retrieve the version, we compare it against a predefined list of vulnerable AOS versions. If the version falls within this list, the device is flagged as potentially vulnerable.

2024-11-13 14:32 UTC, ErebusZ approved these changes

2024-11-13 14:33 UTC, benyissa commented on agent/exploits/cve_2024_42509.py
> +            return ver.parse(version) <= ver.parse(threshold_version)
```suggestion
            return ver.parse(version) <= ver.parse(VULNERABLE_VERSIONS[family])
```

2024-11-13 15:02 UTC, PiranhaSa commented on tests/exploits/cve_2024_42509_test.py
> +def testCVE202442509_whenVulnerable_reportFinding(mocker: plugin.MockerFixture) -> None:
if it works for one and the same logic is repeated for the others , why ?

2024-11-13 15:07 UTC, PiranhaSa commented on agent/exploits/cve_2024_42509.py
> +            return ver.parse(version) <= ver.parse(threshold_version)
I think mine is more clear

2024-11-13 16:36 UTC, 3asm commented on agent/exploits/cve_2024_42509.py
> +        hlapi.ObjectType(hlapi.ObjectIdentity("1.3.6.1.2.1.1.1.0")),  # sysDescr OID
I would put this in a const.

2024-11-13 16:37 UTC, 3asm commented on agent/exploits/cve_2024_42509.py
> +        if version and _is_version_vulnerable(version):
```suggestion
        if version is not None and _is_version_vulnerable(version) is True:
```

2024-11-13 16:40 UTC, ErebusZ commented on agent/exploits/cve_2024_42509.py
> +            return ver.parse(version) <= ver.parse(threshold_version)
+1 to @PiranhaSa

2024-11-13 16:54 UTC, mohsinenar requested changes

2024-11-13 16:54 UTC, mohsinenar commented on agent/exploits/cve_2024_42509.py
> +    elif error_status:
Excplict!

2024-11-13 17:02 UTC, rabsondev commented on agent/exploits/cve_2024_42509.py
> +from agent import exploits_registry
```suggestion
from pysnmp import hlapi
from packaging import version as ver
from ostorlab.agent.kb import kb
from ostorlab.agent.mixins import agent_report_vulnerability_mixin

from agent import definitions
from agent import exploits_registry
```

2024-11-13 17:04 UTC, rabsondev commented on tests/exploits/cve_2024_42509_test.py
> +from agent.exploits import cve_2024_42509
```suggestion
from unittest import mock

from pytest_mock import plugin

from agent import definitions
from agent.exploits import cve_2024_42509
```

2024-11-13 17:14 UTC, adnaneserrar commented on agent/exploits/cve_2024_42509.py
> +            if match:
+1

2024-11-14 08:30 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_42509.py
> +DEFAULT_TIMEOUT = 30
They say use `datetime.timedelta(seconds=30)`

2024-11-14 09:37 UTC, PiranhaSa commented on agent/exploits/cve_2024_42509.py
> +DEFAULT_TIMEOUT = 30
In this case it should be int because the UdpTransportTarget timeout is needing an int

2024-11-14 10:46 UTC, 3asm approved these changes

2024-11-14 10:47 UTC, merged