Set max redirections attribute
Ostorlab/agent_asteroid pull request #38
Opened 2023-12-19 13:25 UTC by elyousfi5

2023-12-19 13:48 UTC, PiranhaSa commented on agent/exploits/cve_2019_12989__cve_2019_12991.py
> +        self.session.max_redirects = MAX_REDIRECTS
you can add verify=False here

2023-12-19 13:49 UTC, PiranhaSa commented on agent/exploits/cve_2019_7193.py
> +        self.session.max_redirects = MAX_REDIRECTS
Same here

2023-12-19 14:48 UTC, BlueSquare1 commented on agent/exploits/cve_2014_0780.py
> +        self.session.verify = False
I think it would be better to have this in a separate file and import it in all exploits so we can apply any change to all exploits without having to modify each exploit separately

2023-12-19 14:58 UTC, 3asm requested changes

2023-12-19 14:58 UTC, 3asm commented on agent/asteroid_agent.py
> +                        e,
This should not be here, the redirect is a case of the rule. Rules should check it.

2023-12-19 14:58 UTC, 3asm commented on agent/exploits/cve_2014_0780.py
> +        self.session = requests.Session()
Why use self.session. This has a risk of polluting the session across runs. We should init the session in the execution of the rule and that's it.

2023-12-19 14:58 UTC, 3asm commented on tests/exploits/cve_2014_0780_test.py
> +    assert exploit_instance.session.max_redirects == 2
These are not needed and also not useful. You are checking a value you are setting, not a behavior you are monitoring.

2023-12-19 15:22 UTC, benyissa commented on agent/asteroid_agent.py
> +                        e,
In this case, it should be inside the accept method.

2023-12-19 16:28 UTC, elyousfi5 commented on agent/exploits/cve_2014_0780.py
> +        self.session.verify = False
Good idea, but there are differences between them. For example verify in some its false and in some its not set (by default True). Like this each one have its conf.

2023-12-20 16:52 UTC, BlueSquare1 commented on agent/exploits/cve_2014_0780.py
> +        self.session.verify = False
> Good idea, but there are differences between them. For example verify in some its false and in some its not set (by default True). Like this each one have its conf.

I don't see a case where verify should be False, also in the cases where we need very specific settings we can just create a new session

2023-12-20 16:59 UTC, 3asm approved these changes

2023-12-20 17:00 UTC, deadly-panda commented on agent/exploits/cve_2018_14558.py
> +            resp = session.get(target_uri, verify=False, timeout=DEFAULT_TIMEOUT)
Why is there 2 styles of specifying verify=False? once as an arg, once as an attribute  to the session instance ?

2023-12-20 17:19 UTC, deadly-panda approved these changes

2023-12-20 17:22 UTC, merged