Add detection for: CVE-2024-21733 (using version check)
Ostorlab/agent_asteroid pull request #46
Opened 2024-01-31 10:54 UTC by BlueSquare1

2024-01-31 11:09 UTC, PiranhaSa commented on agent/exploits/cve_2024_21733.py
> +            targeted_by_ransomware=True,
is these true for the moment ?

2024-01-31 11:18 UTC, PiranhaSa commented on agent/exploits/cve_2024_21733.py
> +                return True
if the response code is 404 -> return false which means is not vulnerable ,  but in the unit test the vulnerable case : return 404

2024-01-31 11:19 UTC, PiranhaSa requested changes

2024-01-31 11:19 UTC, PiranhaSa commented on tests/exploits/cve_2024_21733_test.py
> +        status_code=404,
here we have 404 for the vulnerable case

2024-01-31 11:27 UTC, BlueSquare1 commented on agent/exploits/cve_2024_21733.py
> +            targeted_by_ransomware=True,
Not enough details yet so we'll just keep as False for now

2024-01-31 13:06 UTC, oussamaessaji commented on agent/exploits/cve_2024_21733.py
> +    def check(self, target: definitions.Target) -> list[definitions.Vulnerability]:
Docstring!

2024-01-31 13:07 UTC, oussamaessaji commented on agent/exploits/cve_2024_21733.py
> +    def accept(self, target: definitions.Target) -> bool:
Docstring

2024-01-31 13:18 UTC, PiranhaSa approved these changes

2024-01-31 13:18 UTC, 3asm requested changes

2024-01-31 13:18 UTC, 3asm commented on agent/exploits/cve_2024_21733.py
> +CHECK_ENDPOINTS = ["/docs/RELEASE-NOTES.txt", "/404", "/"]
Are these always there?

2024-01-31 17:18 UTC, mohsinenar commented on agent/exploits/cve_2024_21733.py
> +                return False
If an exception is raised, you should attempt the next endpoint instead of returning immediately.

2024-01-31 17:19 UTC, mohsinenar requested changes

2024-01-31 17:19 UTC, mohsinenar commented on agent/exploits/cve_2024_21733.py
> +        session.verify = False
Can't you inline those?

2024-01-31 17:19 UTC, mohsinenar commented on agent/exploits/cve_2024_21733.py
> +                return []
Same comment here, try the next endpoint!

2024-01-31 18:37 UTC, benyissa commented on agent/exploits/cve_2024_21733.py
> +        session.verify = False
+1

2024-02-01 11:50 UTC, BlueSquare1 commented on agent/exploits/cve_2024_21733.py
> +        session.verify = False
I'm keeping it consistent with other code because this part will be refactored later to have a centralized request handling.

2024-02-01 11:50 UTC, BlueSquare1 commented on agent/exploits/cve_2024_21733.py
> +CHECK_ENDPOINTS = ["/docs/RELEASE-NOTES.txt", "/404", "/"]
We already have a pending research project for request smuggling, will add a TODO for it.

2024-02-01 13:58 UTC, 3asm commented on agent/exploits/cve_2024_21733.py
> +CHECK_ENDPOINTS = ["/docs/RELEASE-NOTES.txt", "/404", "/"]
Request smuggling should not care about this finding. This finding should care about request smuggling. The `TODO` has only sense here.

2024-02-01 14:54 UTC, BlueSquare1 commented on agent/exploits/cve_2024_21733.py
> +CHECK_ENDPOINTS = ["/docs/RELEASE-NOTES.txt", "/404", "/"]
That's what I did actually, I added a ticket reference for better traceability

2024-02-01 16:00 UTC, 3asm approved these changes

2024-02-01 16:00 UTC, merged