Add detection for CVE-2023-43770
Ostorlab/agent_asteroid pull request #47
Opened 2024-02-23 14:52 UTC by BlueSquare1

2024-02-23 15:12 UTC, benyissa commented on agent/exploits/cve_2023_43770.py
> +    def _parse_rc_version(self, raw_version: str) -> version.Version:
I would move  '_parse_rc_version'  outside the class , so it will be clear that this function is not tied to the class's state or behavior. and we can call it from anywhere in the code without needing an instance of a class.

same for _create_vulnerability

2024-02-26 00:21 UTC, 3asm requested changes

2024-02-26 00:21 UTC, 3asm commented on agent/exploits/cve_2023_43770.py
> +        self.session = session
We keep writing the same code. Please write a WebExploit that have these and avoid repeating the same code over and over.

2024-02-26 09:35 UTC, PiranhaSa commented on agent/exploits/cve_2023_43770.py
> +            targeted_by_nation_state=False,
I think it's targeted

2024-02-26 11:01 UTC, 3asm approved these changes

2024-02-26 11:01 UTC, merged