Add log to Agent Asteroid
Ostorlab/agent_asteroid pull request #56
Opened 2024-03-11 16:25 UTC by elyousfi5

2024-03-11 16:39 UTC, rabsondev approved these changes

2024-03-11 18:04 UTC, BlueSquare1 commented on agent/asteroid_agent.py
> +                logger.info("Found %d vulnerabilities", len(target_vulnz.result()))
Can this message be more specific to tell which target the vulnerabilities were found in?

2024-03-12 12:24 UTC, PiranhaSa approved these changes

2024-03-12 14:31 UTC, benyissa requested changes
I'm not sure if this will work. since targets are generators.

Please add a unit test or a screenshot to prove that it works.

2024-03-12 16:05 UTC, ErebusZ approved these changes

2024-03-12 16:06 UTC, ErebusZ commented on agent/asteroid_agent.py
> +            logger.info("Scanning targets `%s`.", targets)
```suggestion
            logger.info("Scanning targets `%s`.", list(targets))
```

2024-03-13 13:09 UTC, merged