Catch the error coming from wrap_socket
Ostorlab/agent_asteroid pull request #71
Opened 2024-05-07 13:30 UTC by PiranhaSa

![image](https://github.com/Ostorlab/agent_asteroid/assets/146742880/c2016c3e-8ec7-4a00-a5cf-5caf05495731)

2024-05-07 15:53 UTC, benyissa approved these changes

2024-05-07 17:38 UTC, oussamaessaji requested changes
Can you update cve_2023_48788 also

2024-05-08 10:07 UTC, 3asm commented
Ping @PiranhaSa

2024-05-08 16:55 UTC, elyousfi5 requested changes
Missing unit tests

2024-05-08 17:04 UTC, 3asm approved these changes

2024-05-08 17:04 UTC, merged