Add CVE-2024-6387
Ostorlab/agent_asteroid pull request #80
Opened 2024-07-04 13:41 UTC by nmasdoufi-ol

2024-07-04 15:13 UTC, rabsondev requested changes

2024-07-04 15:13 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +    except Exception as e:
Do not catch generic exceptions, [be explicit](https://google.github.io/styleguide/pyguide.html#:~:text=Never%20use%20catch%2Dall%20except%3A%20statements%2C%20or%20catch%20Exception%20or%20StandardError%2C%20unless%20you%20are)

2024-07-04 15:13 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +        print(f"Error retrieving SSH banner: {e}")
```suggestion
```

Use `logger` to log the exception.

2024-07-04 15:13 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +from agent.exploits import cve_2024_6387
```suggestion
import re

import requests_mock as req_mock

from agent import definitions
from agent.exploits import cve_2024_6387
```

2024-07-04 15:13 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +        print(f"Accept result for IP address {domain}: {accept}")  # Debugging line
```suggestion
```
Use `logger.debug`

2024-07-04 15:13 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +        ), f"Expected no vulnerabilities for domain {domain}, but found {len(vulnerabilities)}"
```suggestion

        accept = exploit_instance.accept(target)
        
        assert not accept, f"Expected no vulnerability detection for domain {domain}, but accept returned True"

        vulnerabilities = exploit_instance.check(target)
        assert (
            len(vulnerabilities) == 0
        ), f"Expected no vulnerabilities for domain {domain}, but found {len(vulnerabilities)}"
```

2024-07-04 15:13 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +            if version:
Explicit check.

2024-07-04 15:13 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +        print(f"Retrieved banner for {ip_address}:{port} - {banner}")  # Debugging line
```suggestion
```
Use `logger.debug`

2024-07-04 15:13 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +from ostorlab.agent.mixins import agent_report_vulnerability_mixin
```suggestion
import socket
import re

from ostorlab.agent.kb import kb
from ostorlab.agent.mixins import agent_report_vulnerability_mixin

from agent import definitions, exploits_registry
```

2024-07-04 15:31 UTC, oussamaessaji commented on agent/exploits/cve_2024_6387.py
> +def get_ssh_banner(ip_address: str, port: int) -> str:
make it private

2024-07-04 15:32 UTC, mohsinenar requested changes

2024-07-04 15:32 UTC, mohsinenar commented on agent/exploits/cve_2024_6387.py
> +def get_ssh_banner(ip_address: str, port: int) -> str:
Please add docstring.

2024-07-04 15:32 UTC, mohsinenar commented on agent/exploits/cve_2024_6387.py
> +                ]
Move to a const.

2024-07-04 15:32 UTC, mohsinenar commented on agent/exploits/cve_2024_6387.py
> +        if self.accept(target):
Always use explicit check.

2024-07-04 15:38 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6387.py
> +        if self.accept(target):
Done.

2024-07-04 15:38 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6387.py
> +                ]
Done.

2024-07-04 15:38 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6387.py
> +def get_ssh_banner(ip_address: str, port: int) -> str:
Done.

2024-07-04 15:39 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6387.py
> +            if version:
Done

2024-07-04 15:39 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6387.py
> +        print(f"Retrieved banner for {ip_address}:{port} - {banner}")  # Debugging line
Done

2024-07-04 15:39 UTC, nmasdoufi-ol commented on tests/exploits/cve_2024_6387_test.py
> +        print(f"Accept result for IP address {domain}: {accept}")  # Debugging line
Done.

2024-07-05 09:19 UTC, rabsondev requested changes

2024-07-05 09:19 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +        logger.error(f"Unexpected error retrieving SSH banner: {e}")
```suggestion
```
Remove `except Exception as e:`

2024-07-05 09:19 UTC, rabsondev commented on agent/exploits/cve_2024_6387.py
> +            if version:
Check is still not explicit.

2024-07-05 09:19 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +        logger.debug(f"Accept result for IP address {domain}: {accept}")
I don't think this is needed int the unit test.

2024-07-05 09:19 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +        logger.debug(f"Accept result for IP address {domain}: {accept}")
Same here, just remove this line.

2024-07-05 09:20 UTC, nmasdoufi-ol commented on tests/exploits/cve_2024_6387_test.py
> +        logger.debug(f"Accept result for IP address {domain}: {accept}")
The logger.debug line?

2024-07-05 09:21 UTC, rabsondev commented on tests/exploits/cve_2024_6387_test.py
> +        logger.debug(f"Accept result for IP address {domain}: {accept}")
Yes...it's just a unit test, so I don't think having the line is useful.

2024-07-05 09:21 UTC, mohsinenar submitted a review, later dismissed

2024-07-05 09:21 UTC, mohsinenar commented on tests/exploits/cve_2024_6387_test.py
> +        logger.debug(f"Accept result for IP address {domain}: {accept}")
No need for logs inside a test.

2024-07-05 09:21 UTC, mohsinenar commented on tests/exploits/cve_2024_6387_test.py
> +    vulnerable_domains = ["129.114.63.103"]
Is this a dummy value?

2024-07-05 09:25 UTC, nmasdoufi-ol commented on tests/exploits/cve_2024_6387_test.py
> +    vulnerable_domains = ["129.114.63.103"]
The script will go through IPs and domains and checks for the SSH banner. The IP mentioned there is real.

2024-07-05 09:29 UTC, elyousfi5 commented on agent/exploits/cve_2024_6387.py
> +            banner = sock.recv(1024).decode().strip()
there numbers can be consts

2024-07-05 09:29 UTC, elyousfi5 commented on agent/exploits/cve_2024_6387.py
> +        if "OpenSSH" in banner is True:
```suggestion
        if "OpenSSH" in banner:
```

2024-07-05 09:32 UTC, benyissa commented on agent/exploits/cve_2024_6387.py
> +def get_ssh_banner(ip_address: str, port: int) -> str:
```suggestion
def _get_ssh_banner(ip_address: str, port: int) -> str:
```

I would make this method private if it's only used in this module. however if it's public it should be tested.

2024-07-05 16:40 UTC, PiranhaSa commented on agent/exploits/cve_2024_6387.py
> +                if version.group(1) in VULNERABLE_VERSIONS is True:
```suggestion
                if version.group(1) in VULNERABLE_VERSIONS:
```

2024-07-08 06:57 UTC, elyousfi5 commented on tests/exploits/cve_2024_6387_test.py
> +        ), f"Expected vulnerability detection for IP address {domain}, but accept returned False"
```suggestion
        accept = exploit_instance.accept(target)
        
        assert (
            accept is True
        ), f"Expected vulnerability detection for IP address {domain}, but accept returned False"
```

2024-07-08 06:57 UTC, elyousfi5 commented on tests/exploits/cve_2024_6387_test.py
> +        ), f"Expected no vulnerabilities for domain {domain}, but found {len(vulnerabilities)}"
```suggestion

        accept = exploit_instance.accept(target)
        
        assert (
            accept is False
        ), f"Expected no vulnerability detection for domain {domain}, but accept returned True"

        vulnerabilities = exploit_instance.check(target)
        
        assert (
            len(vulnerabilities) == 0
        ), f"Expected no vulnerabilities for domain {domain}, but found {len(vulnerabilities)}"
```

2024-07-08 09:23 UTC, deadly-panda commented on agent/exploits/cve_2024_6387.py
> +from ostorlab.agent.mixins import agent_report_vulnerability_mixin
```suggestion
import socket
import re
import logging

from ostorlab.agent.kb import kb
from ostorlab.agent.mixins import agent_report_vulnerability_mixin

from agent import definitions, exploits_registry
```
Imports usually  follow this pattern:
standard library modules
`\n`
3rd party packages
`\n`
Your code

2024-07-08 09:27 UTC, deadly-panda commented on agent/exploits/cve_2024_6387.py
> +            details = f"{target.origin} is vulnerable to {VULNERABILITY_REFERENCE}, {VULNERABILITY_TITLE}"
shouldn't this be : cve-xx `colon` title ? instead of comma?

2024-07-08 09:27 UTC, deadly-panda commented on tests/exploits/cve_2024_6387_test.py
> +from agent import definitions
```suggestion
from unittest.mock import patch

from agent import definitions
```

2024-07-08 09:28 UTC, deadly-panda commented on tests/exploits/cve_2024_6387_test.py
> +    return definitions.Target(scheme, domain, port)
is this really needed ? just inline in the tests:
`target = definitions.Target(scheme="ssh", domain="dummy_vulnerable_ip", port=22)`

2024-07-08 09:31 UTC, deadly-panda commented on tests/exploits/cve_2024_6387_test.py
> +def test_open_ssh_exploit_when_vulnerable_report_finding(
Unit test names usually follow this pattern:
`testWhatAreYouTesting_whenConditionForTheTest_shouldExpectedBehavior`

2024-07-08 09:32 UTC, deadly-panda commented on tests/exploits/cve_2024_6387_test.py
> +def test_open_ssh_exploit_when_vulnerable_report_finding(
Please apply to the rest

2024-07-08 10:00 UTC, deadly-panda commented on tests/exploits/cve_2024_6387_test.py
> +def test_accept_whenVulnerableBanner_shouldReturnTrue(
`testAcceptExploit_whenVulnerableBanner_shouldReturnTrue`

2024-07-08 14:53 UTC, 3asm requested changes

2024-07-08 14:53 UTC, 3asm commented on tests/exploits/cve_2024_6387_test.py
> +@patch("agent.exploits.cve_2024_6387._get_ssh_banner")
Since you are patching it, expose it `get_ssh_banner` instead of `_get_xxx`. Might as put it in a common folder for shared usage.

2024-07-08 17:42 UTC, 3asm approved these changes

2024-07-08 17:42 UTC, merged