Add CVE-2024-6745
Ostorlab/agent_asteroid pull request #84
Opened 2024-07-17 17:01 UTC by nmasdoufi-ol

2024-07-17 17:17 UTC, mohsinenar submitted a review, later dismissed

2024-07-17 17:17 UTC, mohsinenar commented on agent/exploits/cve_2024_6745.py
> +            return False
```suggestion
            return response.status_code == 200 and  "action ='adminauthenticate.php'" in response.text
```

2024-07-17 17:17 UTC, mohsinenar commented on agent/exploits/cve_2024_6745.py
> +            list[definitions.Vulnerability]: List of vulnerabilities found (empty if none).
No need to put types in docstring!

2024-07-17 17:17 UTC, mohsinenar commented on agent/exploits/cve_2024_6745.py
> +            for payload in PAYLOADS:
Wrapping the whole loop in try-catch means that if all the payloads worked and the last one failed, nothing will be reported!

2024-07-17 17:17 UTC, mohsinenar commented on agent/exploits/cve_2024_6745.py
> +    def exploit(self, target: definitions.Target) -> list[definitions.Vulnerability]:
Why you added the method `exploit` if it's just calling `check`?

2024-07-17 17:17 UTC, mohsinenar commented on tests/exploits/cve_2024_6745_test.py
> +    assert not exploit_instance.accept(target), "The target should be reported as safe."
```suggestion
    assert exploit_instance.accept(target) is False, "The target should be reported as safe."
```

2024-07-17 18:20 UTC, 3asm requested changes

2024-07-17 18:20 UTC, 3asm commented on agent/exploits/cve_2024_6745.py
> +            return False
I prefer the explicit ones, clearer expectation that the output is bool.

2024-07-17 18:20 UTC, 3asm commented on tests/exploits/cve_2024_6745_test.py
> +    assert exploit_instance.accept(
Why check not ran in the unit test?

2024-07-18 07:23 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6745.py
> +            for payload in PAYLOADS:
My bad.

2024-07-18 07:54 UTC, oussamaessaji commented on tests/exploits/cve_2024_6745_test.py
> +    assert not exploit_instance.accept(target), "The target should be reported as safe."
please excplicit

2024-07-18 08:58 UTC, deadly-panda commented on agent/exploits/cve_2024_6745.py
> +    technical_detail = f"{target.origin}/adminauthenticate.php is vulnerable to {VULNERABILITY_REFERENCE}, {VULNERABILITY_TITLE}"
```suggestion
    technical_detail = f"{target.origin}/adminauthenticate.php is vulnerable to {VULNERABILITY_REFERENCE}: {VULNERABILITY_TITLE}"
```

2024-07-18 09:09 UTC, PiranhaSa commented on agent/exploits/cve_2024_6745.py
> +                ):
the same code for check and accept ? isn't this suppose to be 302 code

2024-07-18 09:10 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6745.py
> +                ):
yes but in the final page there should be a 200 OK and `action ='adminauthenticate.php'` in the response.

2024-07-18 09:12 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6745.py
> +    def exploit(self, target: definitions.Target) -> list[definitions.Vulnerability]:
Removed.

2024-07-18 09:18 UTC, 3asm requested changes

2024-07-18 09:18 UTC, 3asm commented on tests/exploits/cve_2024_6745_test.py
> +    )
```suggestion
    vulnerabilities = exploit_instance.check(target)
    vulnerability = vulnerabilities[0]

    assert (
        exploit_instance.accept(target) is True
    ), "The target should be reported as vulnerable."

    assert vulnerability.entry.title == "SQL Injection in Simple Ticket Booking"
    assert (
        vulnerability.technical_detail
        == "http://example.com:80/adminauthenticate.php is vulnerable to CVE-2024-6745, SQL Injection in Simple "
        "Ticket Booking"
    )
```

It makes more sense to start with accept, assert on it. Then do check. Would even separate the test to test only thing at a time.

2024-07-18 09:22 UTC, nmasdoufi-ol commented on tests/exploits/cve_2024_6745_test.py
> +    )
Done.

2024-07-18 09:38 UTC, PiranhaSa commented on agent/exploits/cve_2024_6745.py
> +                )
can you add allow_redirects=True to follow the edirection

2024-07-18 09:38 UTC, PiranhaSa commented on agent/exploits/cve_2024_6745.py
> +                and "action ='adminauthenticate.php'" in response.text
no need ? 
```suggestion
                response.status_code == 200
                and "action ='adminauthenticate.php'" in response.text
```

2024-07-18 09:46 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_6745.py
> +                )
Done.

2024-07-18 10:18 UTC, 3asm approved these changes

2024-07-18 10:19 UTC, merged