Add detection by version for cve_2024_6385
Ostorlab/agent_asteroid pull request #86
Opened 2024-07-22 15:30 UTC by PiranhaSa

2024-07-22 16:36 UTC, mohsinenar commented on agent/definitions.py
> +    risk_rating: str = "CRITICAL"
We default risk rating to `CRITICAL`??

2024-07-22 18:37 UTC, ErebusZ commented on agent/definitions.py
> +    risk_rating: str = "CRITICAL"
It was hardcoded in webexploit.WebExploit

2024-07-23 01:01 UTC, 3asm requested changes

2024-07-23 07:44 UTC, deadly-panda approved these changes

2024-07-23 08:03 UTC, PiranhaSa commented on agent/definitions.py
> +    risk_rating: str = "CRITICAL"
yes that's what we said

2024-07-23 09:34 UTC, nmasdoufi-ol approved these changes

2024-07-23 10:02 UTC, PiranhaSa commented on agent/exploits/cve_2024_6385.py
> +    "to trigger a pipeline as another user under certain circumstances."
check it now please

2024-07-23 13:18 UTC, 3asm approved these changes

2024-07-23 13:18 UTC, merged