Add CVE-2024-38077
Ostorlab/agent_asteroid pull request #94
Opened 2024-08-12 14:00 UTC by nmasdoufi-ol

2024-08-12 15:26 UTC, benyissa commented on tests/exploits/cve_2024_38077_test.py
> +from unittest import mock
I would use pytest_mock as we did in previous tests for consistency. 

2024-08-12 15:42 UTC, elyousfi5 commented on agent/exploits/cve_2024_38077.py
> +from impacket.uuid import uuidtup_to_bin  # type: ignore
```suggestion
from impacket import uuid  # type: ignore
```

2024-08-12 15:43 UTC, elyousfi5 commented on agent/exploits/cve_2024_38077.py
> +UUID = uuidtup_to_bin(("3d267954-eeb7-11d1-b94e-00c04fa3080d", "1.0"))
```suggestion
UUID = uuid.uuidtup_to_bin(("3d267954-eeb7-11d1-b94e-00c04fa3080d", "1.0"))
```

2024-08-12 15:44 UTC, elyousfi5 commented on agent/exploits/cve_2024_38077.py
> +        dce.set_auth_level(2)
please put numbers as consts

2024-08-12 17:31 UTC, mohsinenar requested changes

2024-08-12 17:31 UTC, mohsinenar commented on agent/exploits/cve_2024_38077.py
> +        return 4
Put in a const!

2024-08-12 17:52 UTC, rabsondev requested changes

2024-08-12 17:52 UTC, rabsondev commented on agent/exploits/cve_2024_38077.py
> +from ostorlab.agent.mixins import agent_report_vulnerability_mixin
```suggestion
import logging

from impacket.dcerpc.v5 import transport, epm  # type: ignore
from impacket.dcerpc.v5.ndr import NDRSTRUCT, NDRCALL  # type: ignore
from impacket.dcerpc.v5.dtypes import PULONG  # type: ignore
from impacket.dcerpc.v5.rpcrt import DCERPCException  # type: ignore
from impacket import uuid  # type: ignore
from ostorlab.agent.kb import kb
from ostorlab.agent.mixins import agent_report_vulnerability_mixin
```

2024-08-12 17:52 UTC, rabsondev commented on agent/exploits/cve_2024_38077.py
> +    except Exception as e:
Is this intentional (catching the generic exception)?

2024-08-12 17:52 UTC, rabsondev commented on agent/exploits/cve_2024_38077.py
> +            return _connect_to_license_server(target.origin) is not None
The function catches `Exception` so why is there a try/except?

2024-08-13 09:03 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_38077.py
> +            return _connect_to_license_server(target.origin) is not None
Some unit tests were failing, that's why I had to add it.

2024-08-13 12:50 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_38077.py
> +            return _connect_to_license_server(target.origin) is not None
I fixed it.

2024-08-13 15:45 UTC, 3asm requested changes

2024-08-13 16:11 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_38077.py
> +from impacket.dcerpc.v5.rpcrt import DCERPCException  # type: ignore
Done.

2024-08-13 16:12 UTC, nmasdoufi-ol commented on agent/exploits/cve_2024_38077.py
> +        return _connect_to_license_server(target.origin) is not None
Thanks  🙏

2024-08-13 17:19 UTC, 3asm approved these changes

2024-08-13 17:19 UTC, 3asm commented on agent/exploits/cve_2024_38077.py
> +from impacket.dcerpc.v5 import ndr, dtypes, rpcrt
Split import, not on the same line.

2024-08-13 17:19 UTC, merged